version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      # Coolify otomatik SSL için gerekli label'lar
      - "coolify.managed=true"
      - "coolify.version=4.0"
      - "coolify.type=application"
      - "traefik.enable=true"
      - "traefik.http.routers.privacy-policy.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.privacy-policy.entrypoints=websecure"
      - "traefik.http.routers.privacy-policy.tls.certresolver=letsencrypt"
      - "traefik.http.services.privacy-policy.loadbalancer.server.port=80"